AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: 'AWS CloudFormation Template for GIVE Transaction Logging.'
Resources:
  transactionLogs:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: transaction-logs-1
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
Outputs:
  TableName:
    Value: !Ref 'transactionLogs'
    Description: Table name of the newly created DynamoDB table
    